runtime: nodejs18
env: standard
instance_class: F1
handlers:
  - url: .*
    script: auto
env_variables:
  DATABASE_URL: >-
    postgresql://marina-neon_owner:6yUZ7KmqdizA@ep-fragrant-shadow-a17yci2r-pooler.ap-southeast-1.aws.neon.tech/marina-neon?sslmode=require
  SECRET: SECRET123
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic
service_account: marina-apps@appspot.gserviceaccount.com